name: PHP-CS-FIXER

on:
  pull_request:
    branches:
      - "dev"
    paths:
      - "composer.json"
      - ".github/workflows/composer-validate.yml"

jobs:
  build:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"
          
      - name: Install Dependency
        run: composer install
        
      - name: Run PHP-CS-FIXER
        run: composer run cs
